### ISSUE TITLE
Why webpack load slow and why load js before css

### ISSUE THREAD

**Issue by jason-jz-zhu** [TodoWishlist/TodoWishlist#12]

**Comment by jason-jz-zhu** [comment]
@QiyuLi 
Webpack, in the development model, may build slow because there may be some others' debug tools. 

There is a way to load basic css at the backend in order to fix the pure html before loading the css. This need to do some research.

**Comment by QiyuLi** [comment]
MERN officials is also experiencing slow build/rebuild. (3 minutes for them)
The reason is the debug tool and webpack need to go through all files from server-side.

I suggest improving this later.

**Comment by jason-jz-zhu** [comment]
Agree with you. 

But one thing, we need to find a solution. After go to the home page, there several seconds show pure html no css.
